# Generated by Django 4.2.2 on 2023-06-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='batch',
        ),
    ]
