# Generated by Django 4.2.2 on 2023-06-21 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Scheduler', '0002_remove_course_batch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='images')),
                ('batch', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='lectures',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Scheduler.courses'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
